<?xml version="1.0" ?>
<robot name="tether" xmlns:xacro="http://ros.org/wiki/xacro">
    
    <!-- Define properties -->
    <xacro:property name="tether_length" value="3" />
    <xacro:property name="tether_radius" value="0.01" />
    <xacro:property name="tether_mass" value="0.1" />
    <xacro:property name="num_elements" value="5" />

    <xacro:property name="elem_length" value="${tether_length/num_elements}" />
    <xacro:property name="elem_mass" value="${tether_mass/num_elements}" />

    <!-- Define link macro -->
    <xacro:macro name="tether_element" params="element_num">
        <link name="element_${element_num}">
            <inertial>
                <origin xyz="${elem_length/2} 0 0" rpy="0 ${pi/2} 0" />
                <mass value="${elem_mass}"/>
                <inertia ixx="${1/12*elem_mass*(3*tether_radius**2 + elem_length**2)}" ixy="0" ixz="0" iyy="${1/12*elem_mass*(3*tether_radius**2 + elem_length**2)}" iyz="0" izz="${1/2*elem_mass*(tether_radius**2)}" />
            </inertial>
            <visual>
                <origin xyz="${elem_length/2} 0 0" rpy="0 ${pi/2} 0" />
                <geometry>
                    <cylinder length="${elem_length}" radius="${tether_radius}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="${elem_length/2} 0 0" rpy="0 ${pi/2} 0" />
                <geometry>
                    <cylinder length="${elem_length}" radius="${tether_radius}"/>
                </geometry>
            </collision>
        </link>
    </xacro:macro>


    <!-- Recursive loop to generate multiple elements and joints for said elements -->
    <xacro:macro name="generate_tether" params="elem_num">
        <!-- Generate element and recurse -->
        <xacro:tether_element element_num="${elem_num}" /> 

        <xacro:if value="${elem_num-1}">
            <xacro:generate_tether elem_num="${elem_num-1}" />
        </xacro:if>

        <!-- Define joints -->
        <xacro:if value="${elem_num-1 > 0}">
            <joint name="joint_${elem_num-1}_to_${elem_num}" type="continuous">
                <axis xyz="0. 0. 1."/>
                <origin xyz="${elem_length} 0 0" rpy="0 0 0"/>
                <parent link="element_${elem_num-1}"/>
                <child link="element_${elem_num}"/>
            </joint>

        </xacro:if>

    </xacro:macro>

    <!-- Call recursive loop to generate tether -->
    <xacro:generate_tether elem_num="${num_elements}" />  

</robot>