/**:
    ros__parameters:
      env: 'sim'
      use_sim_time: false #true
      
      ## DEBUG SETTINGS
      print_desired_load_pose: false # In the gcs background node
      print_debug_msgs: false # In the drone node

      ## LOAD SETTINGS
      load_id: 1
      load_pose_type: 'ground_truth' # quasi-static, visual, ground_truth
      evaluate: true # If you want to evaluate the tracking performance of the load
      show_markers: 2 # Show the detected markers 0 = No, 1 = Yes all, 2 = Drone 1 only # TODO: Replace with ENUM?
      marker_edge_length: 0.08 # m

      ## GCS SETTINGS
      auto_level: 0 # 0 = "Fully manual" - requires checks at intermediate steps, 1 = "semi-automatic" - fewer intermediate steps, 2 = "fully automatic" - turn into offboard mode for completely automatic mission
      #run_load_node_on: 'load' # 'load', 'drone', 'gcs' We can run the load node on the gcs, a load or a drone
      #run_background_node_on: 'load' # 'load', 'drone'
      #run_user_node_on: 'drone' # 'drone', 'gcs'. Running the user node on the drone means that the RC will be used to send offboard transition commands, otherwise they will be sent from the gcs through WiFi
      user_interaction_through_rc: false #Send the user interaction commands from a remote controller (true) or through the ground control station (false)
      phase_change_requests_through_background: true # If true, phase change requests are sent through the gcs background node rather than from the gcs user node directly to the drones

      ## RC SETTINGS
      rc_aux_thresholds: [0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.95] # Aux1 expected values for the different offboard phases: takeoff, formation, engage tension, mission, land, hold (all), kill (all)
      rc_aux_buffer: 0.01 # The +/- range from the above thresholds that are still considered acceptable

      ## DRONE SETTINGS
      first_drone_num: 1 #1
      num_drones: 3
      num_cameras: 2 # 0 if cameras are off
    
      drone_order: [1, 2, 3] #[1, 2, 3] #ACW from load's x axis

      ## FORMATION CONTROL
      kp_formation_load: 0.0 #0.1 #0.5 (for faster, larger radius)
      #r_drones_max_safety: 0.5 # m

      ## PHASE SETTINGS      
      # Mission settings
      mission_circle_r: 2.0 # m
      mission_circle_v: 0.75 # m/s 

      # Drone rate settings
      vel_load_vertical_slow: 0.05 # m/s
      vel_load_vertical_fast: 0.3 # m/s
      #yawspeed_load: 0.393

      vel_drone: 0.1 # m/s
      yawspeed_drone: 0.393 # rad/s    

      # Heights/distances/dimensions
      # Formation dimensions
      height_drone_cs_rel_gnd: 0.0 #0.24 # m
      height_load_cs_rel_gnd: 0.0 #0.1 # m
      height_load_pre_tension: -0.4 # m

      takeoff_height_load: 1.0 #m
      takeoff_height_load_max: 3.0 #m # Safety feature - maximum height load will be commanded to take off

      r_drones_rel_load: 1.25 #1.5 #1.0 # m
      d_drones_rel_min: 0.0 #0.5 #1.0 # m
      d_drones_rel_max: 100.0 #5.0 #2.0 # m

      pos_threshold: 0.3 # m

      drone_yaws_rel_load: [3.141592654, -1.0472, 1.0472] # In rad, for 3 drones, np.array([3,141592654, -np.pi*(2/self.num_drones), np.pi*(2/self.num_drones)])

      # Load and cable dimensions
      cable_length: 2.2 #m
      load_connection_point_r: 0.08 #m

      # Camera and markers
      t_cam_rel_pixhawk: [0.1, 0.03, -0.025] # Camera translation relative to PX4 (i.e. drone body)
      R_cam_rel_pixhawk: [-2.61799, 0.0, -1.570796327] #[-2.0944, 0.0, -1.570796327] # Camera rotation relative to PX4 (i.e. drone body)

      t_marker_rel_load: [0.0, 0.0, 0.1] # Marker translation relative to load
      R_marker_rel_load: [0.0, 0.0, 1.570796327] # Marker rotation relative to load

      # Timings
      # Note cnt thresholds are linked to the timer periods
      timer_period_drone: 0.1 # sec
      timer_period_gcs_user: 0.1 # sec
      timer_period_gcs_background: 0.2 # sec
      timer_period_load: 0.1 # sec

      cnt_threshold_drone_setup: 50 #5/timer_period_drone # Tried 3, sometimes issues (weird circling issue of drone 2)
      cnt_threshold_takeoff_start: 30 #3/timer_period_drone # INCREASE IF NEEDED
      cnt_threshold_takeoff_pre_tension: 50
      cnt_threshold_fully_auto_pre_takeoff: 50
      cnt_threshold_fully_auto_mission: 50
      cnt_threshold_land_pre_descent: 50
      cnt_threshold_land_post_load_down: 50
      cnt_threshold_land_drones: 100
      cnt_threshold_land_pre_disarm: 30

      ## TOPIC NAMES
      topic_img_rgb: /out/camera
      topic_cam_info_color: /out/camera_info
      